In [20]:
import numpy as np

In [21]:
A=np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2],
    [7,5,6]
])

In [22]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [23]:
B=np.array([
    [0,1],
    [-1,3],
    [5,2]
])

In [24]:
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [25]:
### A랑 B는 우리가 원하는 값을 넣어 만든 행렬이고, 만약 random한 값을 넣어 만들고 싶다면
### np.random.rand([행,열])을 사용하면 된다.

In [26]:
C=np.random.rand(3,5)

In [27]:
C

array([[0.28079595, 0.81874938, 0.1880968 , 0.7920981 , 0.15004793],
       [0.16247885, 0.38982914, 0.63662028, 0.38292224, 0.15493148],
       [0.50952947, 0.75170013, 0.31693183, 0.66011984, 0.41223406]])

In [28]:
### 만약 모든 값이 0인 행렬을 만들고 싶다면 np.zeros([행,열])을 사용하면 된다.

In [29]:
D=np.zeros((2,4))

In [30]:
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
#### 만약 A라는 행렬에서 1행 3열의 값을 받아오고 싶다면
A[0,2] #### 를 사용하면 된다.

np.int64(2)

In [32]:
### 행렬 덧셈과 곱셈

In [33]:
#### 행렬 덧셈은 간단하게 같은 위치에 있는 값들끼리 더해주면 된다.
A=np.array([
    [1,1],
    [2,3]
])

B=np.array([
    [3,1],
    [2,4]
])
C=A+B
C
#### 행렬 덧셈은 행과 열의 크기가 같아야지만 가능하다.

array([[4, 2],
       [4, 7]])

In [34]:
### 스칼라 곱
i=5
A=np.array([
    [3,1],
    [2,3]
])
A_=i*A
A_

array([[15,  5],
       [10, 15]])

In [40]:
### 두 행렬의 곱셈, 내적곱과 외적곱
### 내적곱

In [44]:
A=np.array([
    [1,3,1],
    [2,2,1]
])
B=np.array([
    [5,6],
    [4,2],
    [3,1]
])

#### A는 2 x 3 행렬이고, B는 3 x 2 행렬이다.
C=np.dot(A,B) #### 행렬의 곱셈은 np.dot()을 사용한다.
#### np.dot(A,B) == A@B
C #### C는 2 x 2 행렬이 된다.

#### 행렬의 곱셈에서는 행렬 A곱하기 행렬 B와 행렬 B곱하기 행렬 A는 다르다.

array([[20, 13],
       [21, 17]])

In [45]:
### 요소별 곱하기
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
B=np.array([
    [0,1,2],
    [2,0,1],
    [1,2,0]
])
C=A*B #### 행렬의 곱셈은 그냥 *를 사용한다.
C #### C는 3 x 3 행렬이 된다.

array([[ 0,  2,  6],
       [ 8,  0,  6],
       [ 7, 16,  0]])

In [46]:
### 특수 행렬 - 전치행렬, 단위행렬, 역행렬

In [48]:
### 전치행렬 (transposed matrix)
A=np.array([
    [1,2,3],
    [4,5,6]
])
A.T
# 첫번째 행이었던게 첫번째 열이 되고, 두번째 행이었던게 두번째 열이 된다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
### 단위행렬 (identity matrix)
I=np.eye(3)
I
I=np.identity(3)
I
### 단위행렬은 정사각 행렬이어야지만 가능하다.
### 단위행렬은 어떤 행렬 A에 곱해도 A가 나온다.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
### 역행렬 (inverse matrix)
#### 곱했을 때 단위행렬이 나오는 행렬을 역행렬이라고 한다.
A=np.array([
    [3,4],
    [1,2]
])
A_I=np.array([
    [1,-2],
    [-0.5,1.5]
])
B=A@A_I
B
#### 역행렬은 -1을 위에 써서(지수로 써서) 표현한다.
#### 또 모든 행렬에 역행렬이 반드시 존재하지는 않는다.

array([[1., 0.],
       [0., 1.]])

In [59]:
#### 역행렬을 구하는 함수는 np.linalg.pinv()를 사용한다.
A=np.array([
    [3,4],
    [1,2]
])
A_inv=np.linalg.pinv(A)
A_inv

array([[ 1. , -2. ],
       [-0.5,  1.5]])

In [61]:
#### 역행렬이 없는 경우에도 np.linalg.pinv()를 사용하면 유사역행렬이 구해진다.
A=np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2]
])
A_inv=np.linalg.pinv(A)
A@A_inv
#### 대각선에 있는 값들은 1이 나오지만 나머지 값들은 0이 나오지 않는다. 그러나 유사하게 나온다

array([[ 1.00000000e+00,  5.55111512e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 0.00000000e+00,  3.33066907e-16,  1.00000000e+00]])